# Generated by Django 3.0.3 on 2020-06-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_popuate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('france', models.FloatField(null=True)),
                ('germany', models.FloatField(null=True)),
                ('korea', models.FloatField(null=True)),
                ('us', models.FloatField(null=True)),
                ('uk', models.FloatField(null=True)),
            ],
        ),
    ]
